"""init

Revision ID: 8f19855d58d1
Revises: d9b71da1f704
Create Date: 2025-10-15 13:06:26.540820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f19855d58d1'
down_revision = 'd9b71da1f704'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.Unicode(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups')),
    sa.UniqueConstraint('group_name', name=op.f('uq_groups_group_name')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.Unicode(length=128), nullable=True),
    sa.Column('user_password', sa.Unicode(length=256), nullable=True),
    sa.Column('email', sa.Unicode(length=100), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('security_code', sa.Unicode(length=256), nullable=True),
    sa.Column('last_login_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('registered_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('security_code_date', sa.TIMESTAMP(), server_default='2000-01-01 01:01', nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('user_name', name=op.f('uq_users_user_name')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('external_identities',
    sa.Column('external_id', sa.Unicode(length=255), nullable=False),
    sa.Column('external_user_name', sa.Unicode(length=255), nullable=True),
    sa.Column('local_user_id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.Unicode(length=50), nullable=False),
    sa.Column('access_token', sa.Unicode(length=512), nullable=True),
    sa.Column('alt_token', sa.Unicode(length=512), nullable=True),
    sa.Column('token_secret', sa.Unicode(length=512), nullable=True),
    sa.ForeignKeyConstraint(['local_user_id'], ['users.id'], name=op.f('fk_external_identities_local_user_id_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('external_id', 'local_user_id', 'provider_name', name='pk_external_identities'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('groups_permissions',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('perm_name', sa.Unicode(length=64), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_groups_permissions_group_id_groups'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'perm_name', name='pk_groups_permissions'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('resources',
    sa.Column('resource_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('ordering', sa.Integer(), nullable=False),
    sa.Column('resource_name', sa.Unicode(length=100), nullable=False),
    sa.Column('resource_type', sa.Unicode(length=30), nullable=False),
    sa.Column('owner_group_id', sa.Integer(), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_group_id'], ['groups.id'], name=op.f('fk_resources_owner_group_id_groups'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_resources_owner_user_id_users'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['resources.resource_id'], name=op.f('fk_resources_parent_id_resources'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('resource_id', name=op.f('pk_resources')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_resources_owner_group_id'), 'resources', ['owner_group_id'], unique=False)
    op.create_index(op.f('ix_resources_owner_user_id'), 'resources', ['owner_user_id'], unique=False)
    op.create_table('users_groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_users_groups_group_id_groups'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_users_groups_user_id_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'user_id', name=op.f('pk_users_groups')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('users_permissions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('perm_name', sa.Unicode(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_users_permissions_user_id_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'perm_name', name='pk_users_permissions'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('entries',
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('some_property', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.resource_id'], name=op.f('fk_entries_resource_id_resources'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resource_id', name=op.f('pk_entries')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('groups_resources_permissions',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('perm_name', sa.Unicode(length=50), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_groups_resources_permissions_group_id_groups'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.resource_id'], name=op.f('fk_groups_resources_permissions_resource_id_resources'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'resource_id', 'perm_name', name='pk_groups_resources_permissions '),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('users_resources_permissions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('perm_name', sa.Unicode(length=64), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.resource_id'], name=op.f('fk_users_resources_permissions_resource_id_resources'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_users_resources_permissions_user_id_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'resource_id', 'perm_name', name='pk_users_resources_permissions '),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_resources_permissions')
    op.drop_table('groups_resources_permissions')
    op.drop_table('entries')
    op.drop_table('users_permissions')
    op.drop_table('users_groups')
    op.drop_index(op.f('ix_resources_owner_user_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_owner_group_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_table('groups_permissions')
    op.drop_table('external_identities')
    op.drop_table('users')
    op.drop_table('groups')
    # ### end Alembic commands ###
